Velly Chauke name: CI

on: [push]
SVC Project Solution (Pty) Ltd 
jobs:
  Abraham Van Wyk Street Plot NO 1 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
